# generated by datamodel-codegen:
#   filename:  https://api.dev-cinescope.coconutqa.ru/swagger-json
#   timestamp: 2026-03-19T11:40:29+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, confloat, ConfigDict


class Location(Enum):
    MSK = "MSK"
    SPB = "SPB"


class SortOrder(Enum):
    ASC = "ASC"
    DESC = "DESC"


class MovieResponse(BaseModel):
    model_config = ConfigDict(use_enum_values=True, from_attributes=True)

    id: int = Field(..., examples=[2])
    name: str = Field(..., examples=["Название фильма"])
    price: float = Field(..., examples=[200])
    description: str = Field(..., examples=["Описание фильма"])
    location: Location = Field(..., examples=["MSK"])
    published: bool = Field(..., examples=[True])
    genreId: float = Field(..., examples=[1])
    genre: dict[str, Any] = Field(..., examples=[{"name": "Драма"}])
    createdAt: AwareDatetime = Field(..., examples=["2024-02-28T04:28:15.965Z"])
    imageUrl: str | None = Field(..., examples=["https://image.url"])
    rating: confloat(ge=0.0, le=10.0) = Field(..., examples=[5])

    @classmethod
    def get_keys_list(cls, keys_to_skip: list[str] | None = None):
        keys = cls.model_fields.keys()
        keys_list = list(keys)

        if keys_to_skip:
            return [x for x in keys_list if x not in keys_to_skip]

        return keys_list


class FindAllMoviesResponse(BaseModel):
    movies: list[MovieResponse]
    count: float = Field(..., examples=[13])
    page: float = Field(..., examples=[1])
    pageSize: float = Field(..., examples=[10])
    pageCount: float = Field(..., examples=[2])


class FindMoviesQuery(BaseModel):
    pageSize: int
    page: int
    minPrice: int
    maxPrice: int
    locations: list[Location]
    published: bool
    genreId: int
    createdAt: SortOrder


class MovieReviewResponse(BaseModel):
    userId: str = Field(..., examples=["67723995-bae2-42a4-971b-14fe801c77a5"])
    rating: float = Field(..., examples=[5])
    text: str = Field(..., examples=["Cool!"])
    hidden: bool = Field(..., examples=[False])
    createdAt: AwareDatetime = Field(..., examples=["2024-02-29T06:48:38.551Z"])
    user: dict[str, Any] = Field(..., examples=[{"fullName": "Артём"}])


class FindOneMovieResponse(BaseModel):
    id: float = Field(..., examples=[2])
    name: str = Field(..., examples=["Название фильма"])
    price: float = Field(..., examples=[200])
    description: str = Field(..., examples=["Описание фильма"])
    imageUrl: str = Field(..., examples=["https://image.url"])
    location: Location = Field(..., examples=["MSK"])
    published: bool = Field(..., examples=[True])
    genreId: float = Field(..., examples=[1])
    genre: dict[str, Any] = Field(..., examples=[{"name": "Драма"}])
    createdAt: AwareDatetime = Field(..., examples=["2024-02-28T04:28:15.965Z"])
    rating: confloat(ge=0.0, le=5.0) = Field(..., examples=[5])
    reviews: list[MovieReviewResponse]


class CreateMovieDto(BaseModel):
    name: str
    imageUrl: str | None = "https://example.com/image.png"
    price: float
    description: str
    location: Location
    published: bool
    genreId: float


class EditMovieDto(BaseModel):
    name: str | None = None
    description: str | None = None
    price: float | None = None
    location: Location | None = None
    imageUrl: str | None = None
    published: bool | None = None
    genreId: float | None = None


class CreateReviewDto(BaseModel):
    rating: float = Field(..., examples=[4])
    text: str = Field(..., examples=["Хорошее кино"])


class GenreResponse(BaseModel):
    id: float = Field(..., description="Идентификатор жанра", examples=[1])
    name: str = Field(..., examples=["Название жанра"])


class CreateGenreDto(BaseModel):
    name: str = Field(..., examples=["Название жанра"])
