# generated by datamodel-codegen:
#   filename:  https://auth.dev-cinescope.coconutqa.ru/swagger-json
#   timestamp: 2026-04-16T11:34:11+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import AwareDatetime, BaseModel, Field, field_validator, ConfigDict


class Role(Enum):
    USER = "USER"
    ADMIN = "ADMIN"
    SUPER_ADMIN = "SUPER_ADMIN"


class UserData(BaseModel):
    id: str
    email: str
    fullName: str
    roles: list[Role]


class AuthSuccessResponse(BaseModel):
    user: UserData
    accessToken: str
    refreshToken: str
    expiresIn: int


class UserResponse(BaseModel):
    id: str = Field(
        ...,
        description="Идентификатор пользователя",
        examples=["8cbabbe9-5fff-4dbe-a77e-104bf4e63dbe"],
    )
    email: str = Field(
        ..., description="Идентификатор пользователя", examples=["test@mail.ru"]
    )
    fullName: str = Field(..., examples=["ФИО пользователя"])
    roles: list[Role]
    verified: bool
    createdAt: AwareDatetime
    banned: bool


class AuthPayload(BaseModel):
    email: str = Field(..., examples=["test@email.com"])
    password: str = Field(..., examples=["12345678Aa"])


class CreateUserDto(BaseModel):
    model_config = ConfigDict(use_enum_values=True)

    fullName: str
    email: str = Field(..., examples=["test@email.com"])
    password: str
    passwordRepeat: str = Field(
        ...,
        examples=["12345678Aa"],
        min_length=8,
        description="Пароли должны совпадать",
    )
    verified: Optional[bool] = True
    banned: Optional[bool] = False
    roles: list[Role] = [Role.USER]

    @field_validator("email")
    @classmethod
    def validate_email(cls, value: str):
        if "@" not in value:
            raise ValueError("Email должен содержать @")
        return value

    @field_validator("passwordRepeat")
    @classmethod
    def check_password_repeat(cls, value: str, info) -> str:
        if "password" in info.data and value != info.data["password"]:
            raise ValueError("Пароли не совпадают")
        return value


class EditUserDto(BaseModel):
    roles: list[Role] = Field(..., description="Роли пользователя")
    verified: bool = Field(..., description="Пользователь подтверждён")
    banned: bool = Field(..., description="Пользователь забанен")


class FindAllUsersResponse(BaseModel):
    users: list[UserResponse] = Field(...)
    count: int = Field(..., examples=[9], ge=1)
    page: int = Field(..., examples=[1], ge=1)
    pageSize: int = Field(..., examples=[10], ge=1)
