# generated by datamodel-codegen:
#   filename:  https://api.dev-cinescope.coconutqa.ru/swagger-json
#   timestamp: 2026-03-19T11:40:29+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, confloat


class Location(Enum):
    MSK = 'MSK'
    SPB = 'SPB'

class SortOrder(Enum):
    ASC = "ASC"
    DESC = "DESC"

class Roles(Enum):
    USER = "USER"
    ADMIN = "ADMIN"

class MovieResponse(BaseModel):
    id: float = Field(..., examples=[2])
    name: str = Field(..., examples=['Название фильма'])
    price: float = Field(..., examples=[200])
    description: str = Field(..., examples=['Описание фильма'])
    imageUrl: str = Field(..., examples=['https://image.url'])
    location: Location = Field(..., examples=['MSK'])
    published: bool = Field(..., examples=[True])
    genreId: float = Field(..., examples=[1])
    genre: dict[str, Any] = Field(..., examples=[{'name': 'Драма'}])
    createdAt: AwareDatetime = Field(..., examples=['2024-02-28T04:28:15.965Z'])
    rating: confloat(ge=0.0, le=5.0) = Field(..., examples=[5])


class FindAllMoviesResponse(BaseModel):
    movies: list[MovieResponse]
    count: float = Field(..., examples=[13])
    page: float = Field(..., examples=[1])
    pageSize: float = Field(..., examples=[10])
    pageCount: float = Field(..., examples=[2])

class FindMoviesQuery(BaseModel):
    pageSize: int
    page: int
    minPrice: int
    maxPrice: int
    locations: list[Location]
    published: bool
    genreId: int
    createdAt: SortOrder

class MovieReviewResponse(BaseModel):
    userId: str = Field(..., examples=['67723995-bae2-42a4-971b-14fe801c77a5'])
    rating: float = Field(..., examples=[5])
    text: str = Field(..., examples=['Cool!'])
    hidden: bool = Field(..., examples=[False])
    createdAt: AwareDatetime = Field(..., examples=['2024-02-29T06:48:38.551Z'])
    user: dict[str, Any] = Field(..., examples=[{'fullName': 'Артём'}])


class FindOneMovieResponse(BaseModel):
    id: float = Field(..., examples=[2])
    name: str = Field(..., examples=['Название фильма'])
    price: float = Field(..., examples=[200])
    description: str = Field(..., examples=['Описание фильма'])
    imageUrl: str = Field(..., examples=['https://image.url'])
    location: Location = Field(..., examples=['MSK'])
    published: bool = Field(..., examples=[True])
    genreId: float = Field(..., examples=[1])
    genre: dict[str, Any] = Field(..., examples=[{'name': 'Драма'}])
    createdAt: AwareDatetime = Field(..., examples=['2024-02-28T04:28:15.965Z'])
    rating: confloat(ge=0.0, le=5.0) = Field(..., examples=[5])
    reviews: list[MovieReviewResponse]


class CreateMovieDto(BaseModel):
    name: str
    imageUrl: str | None = 'https://example.com/image.png'
    price: float
    description: str
    location: Location
    published: bool
    genreId: float

class AuthSuccessResponse(BaseModel):
    user: UserData
    accessToken: str
    refreshToken: str
    expiresIn: int

class UserData(BaseModel):
    id: str
    email: str
    fullName: str
    roles: Roles

class EditMovieDto(BaseModel):
    name: str | None = 'Movie name'
    description: str | None = 'Movie description'
    price: float | None = 100
    location: Location | None = 'SPB'
    imageUrl: str | None = 'https://image.url'
    published: bool | None = True
    genreId: float | None = 1


class CreateReviewDto(BaseModel):
    rating: float = Field(..., examples=[4])
    text: str = Field(..., examples=['Хорошее кино'])


class GenreResponse(BaseModel):
    id: float = Field(..., description='Идентификатор жанра', examples=[1])
    name: str = Field(..., examples=['Название жанра'])


class CreateGenreDto(BaseModel):
    name: str = Field(..., examples=['Название жанра'])
